spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:redisTest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
        max-page-size: 100
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug

jwt:
  token:
    header: "Authorization"
    secret: "mySecret"
    expire-time: 3600000
